<?php

/**
 * @file
 * Code for the hello_world module.
 */

/**
 * Implements hook_theme().
 */
function hello_world_theme($existing, $type, $theme, $path) {
  return array(
    'block_currencies' => array(
      'variables' => array(
        'currencies' => array(),
      ),
    ),
    'block_currencies_v2' => array(
      'variables' => array(
        'currencies' => array(),
      ),
    ),
    'element_current_time' => array(
      'render element' => 'element',
    ),
  );
}

/**
 * Implements hook_entity_type_alter().
 */
function hello_world_entity_type_alter(array &$entity_types) {
  $currency = $entity_types['currency'];
  // TODO: figure out how to add a constraint properly
  $currency->addConstraint('Length', ['max' => 5]);
}
