<?php

/**
 * @file
 * Code for the hello_world module.
 */

/**
 * Implements hook_theme().
 */
function hello_world_theme($existing, $type, $theme, $path) {
  return array(
    'block_currencies' => array(
      'variables' => array(
        'currencies' => array(),
      ),
    ),
    'block_currencies_v2' => array(
      'variables' => array(
        'currencies' => array(),
      ),
    ),
    'element_current_time' => array(
      'render element' => 'element',
    ),
  );
}
